Data Cleaning & Preprocessing

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

1. Handling Missing Values

Missing values are handled to make the dataset complete. Numerical missing values are filled using the median, while categorical missing values are filled using the mode.

In [5]:
df = pd.read_csv("../data/raw data.csv")

In [6]:
df.isnull().sum()

Customer_ID                                0
Age                                        0
Gender                                     0
Income_Level                               0
Marital_Status                             0
Education_Level                            0
Occupation                                 0
Location                                   0
Purchase_Category                          0
Purchase_Amount                            0
Frequency_of_Purchase                      0
Purchase_Channel                           0
Brand_Loyalty                              0
Product_Rating                             0
Time_Spent_on_Product_Research(hours)      0
Social_Media_Influence                   247
Discount_Sensitivity                       0
Return_Rate                                0
Customer_Satisfaction                      0
Engagement_with_Ads                      256
Device_Used_for_Shopping                   0
Payment_Method                             0
Time_of_Purchase                           0
Discount_Used                              0
Customer_Loyalty_Program_Member            0
Purchase_Intent                            0
Shipping_Preference                        0
Time_to_Decision                           0
dtype: int64

In [7]:
# Fill categorical missing values

df["Social_Media_Influence"] = df["Social_Media_Influence"].fillna("Unknown")

In [8]:
df["Engagement_with_Ads"] = df["Engagement_with_Ads"].fillna(
    df["Engagement_with_Ads"].mode()[0]
)

This step handles missing values in categorical columns. Missing values in the Social_Media_Influence column are replaced with the category "Unknown", while missing values in the Engagement_with_Ads column are replaced using the most frequent value (mode). This ensures the dataset remains complete without losing important information.

In [9]:
df.isnull().sum()

Customer_ID                              0
Age                                      0
Gender                                   0
Income_Level                             0
Marital_Status                           0
Education_Level                          0
Occupation                               0
Location                                 0
Purchase_Category                        0
Purchase_Amount                          0
Frequency_of_Purchase                    0
Purchase_Channel                         0
Brand_Loyalty                            0
Product_Rating                           0
Time_Spent_on_Product_Research(hours)    0
Social_Media_Influence                   0
Discount_Sensitivity                     0
Return_Rate                              0
Customer_Satisfaction                    0
Engagement_with_Ads                      0
Device_Used_for_Shopping                 0
Payment_Method                           0
Time_of_Purchase                         0
Discount_Used                            0
Customer_Loyalty_Program_Member          0
Purchase_Intent                          0
Shipping_Preference                      0
Time_to_Decision                         0
dtype: int64

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("../data/raw data.csv")

df.head()

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
0,37-611-6911,22,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,$333.80,...,7,NaN,Tablet,Credit Card,3/1/2024,True,False,Need-based,No Preference,2
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,$222.22,...,5,High,Tablet,PayPal,4/16/2024,True,False,Wants-based,Standard,6
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,$426.22,...,7,Low,Smartphone,Debit Card,3/15/2024,True,True,Impulsive,No Preference,3
3,48-980-6078,29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,$101.31,...,1,NaN,Smartphone,Other,10/4/2024,True,True,Need-based,Express,10
4,91-170-9072,33,Female,Middle,Widowed,High School,Middle,Nara,Furniture,$211.70,...,10,NaN,Smartphone,Debit Card,1/30/2024,False,False,Wants-based,No Preference,4

2. Handling Inconsistencies

In [ ]:
df["Purchase_Amount"] = df["Purchase_Amount"].replace(
    '[\$,]',
    '',
    regex=True
)

<>:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
<>:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
C:\Users\hp\AppData\Local\Temp\ipykernel_21448\3152696860.py:2: SyntaxWarning: "\$" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\$"? A raw string is also an option.
  '[\$,]',

This step removes special symbols such as dollar signs ($) and commas (,) from the Purchase_Amount column. These symbols prevent numerical analysis and machine learning processing. After removing the symbols, the column becomes suitable for conversion into a numerical data type.

In [11]:
# Convert to float

df["Purchase_Amount"] = df["Purchase_Amount"].astype(float)

After removing special symbols from the Purchase_Amount column, the data type is converted into float format. This allows numerical calculations, statistical analysis, visualization, and machine learning operations to be performed correctly.

In [12]:
print(df["Purchase_Amount"].dtype)

float64

This step checks the data type of the Purchase_Amount column after conversion. It verifies that the column has been successfully converted into a numerical float data type for further analysis and machine learning processing.

3. Duplicate Removal

In [13]:
# Check duplicates

df.duplicated().sum()

np.int64(0)

This step checks the dataset for duplicate records using the duplicated() function. Duplicate rows can negatively affect data quality and machine learning performance, so identifying them is important before model training.

In [14]:
# Remove duplicates

df = df.drop_duplicates()

This step removes duplicate records from the dataset using the drop_duplicates() function. Removing duplicate rows improves data quality and prevents repeated information from affecting machine learning model performance.

4. Outlier Treatment

In [15]:
Q1 = df["Purchase_Amount"].quantile(0.25)

Q3 = df["Purchase_Amount"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR

upper = Q3 + 1.5 * IQR

df = df[
    (df["Purchase_Amount"] >= lower) &
    (df["Purchase_Amount"] <= upper)
]

This step detects and removes outliers from the Purchase_Amount column using the Interquartile Range (IQR) method. The first quartile (Q1), third quartile (Q3), and IQR are calculated to determine acceptable value ranges. Values outside the lower and upper bounds are treated as outliers and removed from the dataset to improve data quality and model performance.

5. Feature Engineering

In [9]:
df["Spending_Per_Age"] = (
    df["Purchase_Amount"] / df["Age"]
)

This step creates a new feature called Spending_Per_Age through feature engineering. The feature is calculated by dividing Purchase_Amount by Age, which helps represent customer spending behavior relative to age. Feature engineering can improve machine learning model performance by providing additional useful information.

In [10]:
df.head()

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision,Spending_Per_Age
0,37-611-6911,22,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,333.80,...,NaN,Tablet,Credit Card,3/1/2024,True,False,Need-based,No Preference,2,15.172727
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,222.22,...,High,Tablet,PayPal,4/16/2024,True,False,Wants-based,Standard,6,4.535102
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,426.22,...,Low,Smartphone,Debit Card,3/15/2024,True,True,Impulsive,No Preference,3,17.759167
3,48-980-6078,29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,101.31,...,NaN,Smartphone,Other,10/4/2024,True,True,Need-based,Express,10,3.493448
4,91-170-9072,33,Female,Middle,Widowed,High School,Middle,Nara,Furniture,211.70,...,NaN,Smartphone,Debit Card,1/30/2024,False,False,Wants-based,No Preference,4,6.415152

In [11]:
df.to_csv("../data/cleaned_data.csv", index=False)

print("Saved successfully")
print(df.shape)

Saved successfully
(1000, 29)

This step saves the cleaned and preprocessed dataset into a CSV file inside the data folder. Saving the processed dataset allows it to be reused later for model training and evaluation without repeating preprocessing steps. The dataset shape is also displayed to confirm the number of rows and columns after preprocessing.

In [12]:
# Check final dataset

df.head()

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision,Spending_Per_Age
0,37-611-6911,22,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,333.80,...,NaN,Tablet,Credit Card,3/1/2024,True,False,Need-based,No Preference,2,15.172727
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,222.22,...,High,Tablet,PayPal,4/16/2024,True,False,Wants-based,Standard,6,4.535102
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,426.22,...,Low,Smartphone,Debit Card,3/15/2024,True,True,Impulsive,No Preference,3,17.759167
3,48-980-6078,29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,101.31,...,NaN,Smartphone,Other,10/4/2024,True,True,Need-based,Express,10,3.493448
4,91-170-9072,33,Female,Middle,Widowed,High School,Middle,Nara,Furniture,211.70,...,NaN,Smartphone,Debit Card,1/30/2024,False,False,Wants-based,No Preference,4,6.415152

In [16]:
# Check object/text columns
print(df.select_dtypes(include="object").columns)

Index(['Customer_ID', 'Gender', 'Income_Level', 'Marital_Status',
       'Education_Level', 'Occupation', 'Location', 'Purchase_Category',
       'Purchase_Channel', 'Social_Media_Influence', 'Discount_Sensitivity',
       'Engagement_with_Ads', 'Device_Used_for_Shopping', 'Payment_Method',
       'Time_of_Purchase', 'Purchase_Intent', 'Shipping_Preference'],
      dtype='str')

C:\Users\hp\AppData\Local\Temp\ipykernel_21448\691207635.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include="object").columns)

In [17]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Remove ID-like columns if they exist
drop_cols = ["Customer_ID", "Phone_Number", "Phone", "Email", "Name"]

for col in drop_cols:
    if col in df.columns:
        df = df.drop(col, axis=1)

# Encode remaining categorical columns
le = LabelEncoder()

for col in df.select_dtypes(include="object").columns:
    df[col] = le.fit_transform(df[col].astype(str))

# Define X and y
X = df.drop("Purchase_Intent", axis=1)
y = df["Purchase_Intent"]

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

C:\Users\hp\AppData\Local\Temp\ipykernel_21448\4019810442.py:13: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

This step prepares the dataset for machine learning model training. First, unnecessary ID-like columns such as customer IDs, phone numbers, emails, and names are removed because they do not contribute meaningful information to prediction. Categorical variables are then converted into numerical values using Label Encoding. After encoding, the dataset is divided into independent features (X) and the target variable (y). Finally, StandardScaler is applied to normalize the feature values, ensuring that all variables are on a similar scale and improving machine learning model performance.

In [18]:
import joblib

joblib.dump(scaler, "../models/preprocessing.pkl")

print("Preprocessing pipeline saved")

Preprocessing pipeline saved

This step saves the preprocessing pipeline using joblib. The StandardScaler object is stored in a pickle file so that the same preprocessing transformations can be reused later during model deployment and prediction. Saving the preprocessing pipeline ensures consistency between training data and future input data.